### ISSUE TITLE
TODO: install tools to path and import scripts as modules

### ISSUE THREAD

**Issue by jamestwebber** [czbiohub/utilities#5]
As currently written you kinda need to be in the `utilities/utilities` directory to run things. It'd be nicer if activating the environment put the launcher on your PATH and it knew that scripts would be importable from its directory.

- [x] modify install script to add `aegea_launcher.py` to PATH along with any other useful tools
- [x] add `__init__.py` to the relevant folders so that they can be imported
- [x] modify `aegea_launcher.py` to import things relative to itself rather than from the current working dir
